### PR TITLE
accept bin/rails test:system from Rails5.1

### LINKED ISSUE #16: bin/rails test:system result differs
sample app is https://github.com/naofumi-fujii/my-sample-rails/pull/1/files

without test-unit-rails

```
[naofumi.fujii]$ ./bin/rails test:system
Run options: --seed 37010

# Running:

Puma starting in single mode...
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:51871
Use Ctrl-C to stop
.

Finished in 2.432139s, 0.4112 runs/s, 0.4112 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

with test-unit-rails

```
[naofumi.fujii]$ ./bin/rails test:system
Run options: --seed 14897

# Running:



Finished in 0.000571s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

### PR DESCRIPTION
**Pull request by naofumi-fujii**
fix #16

### CODE REVIEW

**Comment by kou** [comment]
Thanks! Can you confirm that this change solve your problem? If so, I'll merge it.

**Comment by naofumi-fujii** [comment]
i added result with this PR at #16 as comment.
should i do something else?

**Comment by naofumi-fujii** [comment]
built sample app using this pr
https://github.com/naofumi-fujii/my-sample-rails/pull/3/files

**Comment by kou** [comment]
It looks that it works. Thanks!

**Comment by kou** [comment]
I've released a new version.

**Pull request merged**
